#!/usr/bin/env node
// build-app.mjs — inject the canonical engine + MODEL into the standalone
// viz/aging-simulator.html so the app RENDERS using the single-source-of-truth
// math from model/engine.mjs (no duplicated model code in the HTML).
//
// What it does:
//   1. Reads model/engine.mjs and strips the ESM `export`/`import` keywords so
//      the source can run inside a plain (non-module) <script> at file:// scope.
//   2. Reads model/params.json (the MODEL) and serialises it.
//   3. Splices both into viz/aging-simulator.html between delimited markers:
//         // <<<ENGINE-INJECT-START>>> ... // <<<ENGINE-INJECT-END>>>
//      Re-runnable: each run replaces whatever is currently between the markers.
//
// The app's rendering code (outside the markers) calls the inlined
// `simulate(MODEL, opts)` — the SAME function model/test.mjs exercises. There is
// no second copy of the math anywhere in the HTML.
//
// Usage:  node model/build-app.mjs
// Dependency-free, Node ESM, no network.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

const ENGINE_PATH = resolve(HERE, "engine.mjs");
const PARAMS_PATH = resolve(HERE, "params.json");
const HTML_PATH = resolve(ROOT, "viz", "aging-simulator.html");

const START = "// <<<ENGINE-INJECT-START>>>";
const END = "// <<<ENGINE-INJECT-END>>>";

/* ---- 1. engine source, de-ESM'd ---------------------------------------- */
let engineSrc = readFileSync(ENGINE_PATH, "utf8");

// Strip module syntax so it runs in a classic <script>. The engine has NO
// imports; we only need to neutralise `export`. Handle the three forms used:
//   `export function NAME` -> `function NAME`
//   `export { ... };`      -> (removed)
//   `import ...;`          -> (removed, defensive; engine currently has none)
engineSrc = engineSrc
  .replace(/^export\s+function\s+/gm, "function ")
  .replace(/^export\s+\{[^}]*\};?\s*$/gm, "")
  .replace(/^import\s+[^;]*;?\s*$/gm, "");

if (/^\s*export\b/m.test(engineSrc) || /^\s*import\b/m.test(engineSrc)) {
  throw new Error("build-app: residual export/import survived stripping — inspect engine.mjs");
}

/* ---- 2. MODEL ---------------------------------------------------------- */
const modelObj = JSON.parse(readFileSync(PARAMS_PATH, "utf8"));
const modelJson = JSON.stringify(modelObj, null, 2);

/* ---- 3. assemble injected block ---------------------------------------- */
const injected = [
  START,
  "/* ======================================================================",
  "   AUTO-GENERATED by model/build-app.mjs — DO NOT EDIT BETWEEN THE MARKERS.",
  "   Source of truth: model/engine.mjs (math) + model/params.json (MODEL).",
  "   Re-run `node model/build-app.mjs` to regenerate. The app's rendering code",
  "   (below the END marker) consumes simulate(MODEL, opts) from this block.",
  "   ====================================================================== */",
  "/* ---- canonical engine (model/engine.mjs, export/import stripped) ---- */",
  engineSrc.trimEnd(),
  "",
  "/* ---- MODEL (model/params.json) ---- */",
  "const MODEL = " + modelJson + ";",
  "",
  "/* ---- on-load regression assert: baseline male LE ≈ 75.82 ---- */",
  "console.assert(",
  "  Math.abs(simulate(MODEL, { sex: 'male' }).LE - 75.82) < 0.05,",
  "  'engine self-check: baseline male LE expected ≈75.82, got',",
  "  simulate(MODEL, { sex: 'male' }).LE",
  ");",
  END,
].join("\n");

/* ---- 4. splice into HTML between markers -------------------------------- */
let html = readFileSync(HTML_PATH, "utf8");

const startIdx = html.indexOf(START);
const endIdx = html.indexOf(END);
if (startIdx === -1 || endIdx === -1) {
  throw new Error(
    `build-app: injection markers not found in ${HTML_PATH}.\n` +
      `Expected both:\n  ${START}\n  ${END}\n` +
      `Add them (e.g. as the first thing inside the app <script>) and re-run.`
  );
}
if (endIdx < startIdx) {
  throw new Error("build-app: END marker precedes START marker in HTML.");
}

const before = html.slice(0, startIdx);
const after = html.slice(endIdx + END.length);
html = before + injected + after;

writeFileSync(HTML_PATH, html, "utf8");

console.log(
  `build-app: injected engine (${engineSrc.length} chars) + MODEL ` +
    `(${modelObj.nodes.length} nodes / ${modelObj.edges.length} edges) into ` +
    `viz/aging-simulator.html`
);
